apiVersion: v1
kind: ConfigMap
metadata:
  name: global-database-config-v4
  namespace: default
data:
  database.properties: |
    database.url: "https://dbserver.com:3306"
    database.password: "password@1"
