apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  #minReadySeconds: 30
  selector:   
    matchLabels: 
      mylabelapp: webapp
  replicas: 2
  template: 
    metadata:
      labels:
        mylabelapp: webapp
    
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
    
 
---

apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    mylabelapp: queue
    
spec:
  containers:
  - name: queue
    image: richardchesterwood/k8s-fleetman-queue:release1